### ISSUE TITLE
[Suggestion] PlayerIDs for ignored AFK players

### ISSUE THREAD

**Issue by LaFesta1749** [SrLicht/Ultimate-AFK#16]
Is it possible to introduce a configuration file entry enabling the specification of player IDs to be exempted from the AFK timer, akin to the permissions afforded to staff members?

This proposition arises from the prevalence of Exiled usage, where the inability of permissions to traverse between NWApi and Exiled renders the AFK ignore permissions ineffective.

**Comment by SrLicht** [comment]
The plugin is focused for NWAPI users but if you want I can add that configuration but I will not remove the NWAPIPermissionSystem dependency.

**Comment by SrLicht** [comment]
https://github.com/SrLicht/Ultimate-AFK/releases/tag/6.4.4
